# ArgoCD Application — Node Guardian
# 指向 node-guardian 仓库的 deploy/ 目录

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-guardian
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/290298661-pixel/node-guardian.git
    targetRevision: master
    path: deploy/

  destination:
    server: https://kubernetes.default.svc
    namespace: node-guardian-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
